# frozen_string_literal: true

require 'yaml'
require 'time'
require 'terminal-table'
require 'i18n'
require 'colorize'
require 'bcrypt'
require_relative 'lib/assistant'
require_relative 'lib/management/db_reader'
require_relative 'lib/management/input'
require_relative 'lib/management/search'
require_relative 'lib/management/sorting'
require_relative 'lib/management/statistic'
require_relative 'lib/management/stat'
require_relative 'lib/management/output'
require_relative 'lib/management/localization'
require_relative 'lib/management/menu'
require_relative 'lib/app'
require_relative 'lib/management/show_cars'
require_relative 'lib/management/usersignup'
require_relative 'lib/management/userlogin'
