# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@0.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

executors:
  default:
    working_directory: ~/cars_management
    description: Ruby docker
    docker:
      - image: circleci/ruby:3.0.2
caches:
  - &bundle_cache_full v1-cars_management{{ checksum "Gemfile.lock" }}
  - &bundle_cache v1-cars_management

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
            - *bundle_cache
      - run:
          name: install require gems
          command: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle
  run_lefthook:
    description: start lefthook
    steps:
      - run:
          name: lefthook
          command: bundle exec lefthook run pre-commit
jobs:
  build:
    executor: default
    steps:
      - defaults
      - run_lefthook
